# version: "3"

# services: 
#     web:
#         container_name: ${APP_NAME}_web
#         build: 
#             context: ./docker/web
#         ports: 
#             - 9000:80
#         volumes: 
#             - ./:/var/www/app

version: '3'

services:
#   database:
#     container_name: app_db
#     image: postgres
#     restart: always
#     volumes:
#       - dbdata:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_HOST=127.0.0.1
#       - POSTGRES_PASSWORD=secret
#       - POSTGRES_DATABASE=atmlaravel
#     networks:
#       backend:
#         aliases:
#           - app_db
#     ports:
#       - 5432:5432
# #    redis:
#      image: redis:alpine
#      command: redis-server --appendonly yes --appendfsync always --save 900 1 --save 300 10 --save 60 1000
#      volumes:
#        - redis:/data
#      restart: always
#      container_name: redis

  #  The Application

  app:
    build:
      context: ./docker/web
      args:
        uid: ${UID}
    container_name: laravelatm
    volumes:
      - .:/var/www/html
    ports:
      - 8510:80
    networks:
      backend:
        aliases:
          - app
    # depends_on: 
    #   - database

networks:
  backend:
volumes:
  dbdata:
  redis:
  db:
